// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/pvz/v1/pvz.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PVZ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PVZ) Reset() {
	*x = PVZ{}
	mi := &file_api_pvz_v1_pvz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PVZ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVZ) ProtoMessage() {}

func (x *PVZ) ProtoReflect() protoreflect.Message {
	mi := &file_api_pvz_v1_pvz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVZ.ProtoReflect.Descriptor instead.
func (*PVZ) Descriptor() ([]byte, []int) {
	return file_api_pvz_v1_pvz_proto_rawDescGZIP(), []int{0}
}

func (x *PVZ) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PVZ) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type GetPVZListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pvz           []*PVZ                 `protobuf:"bytes,1,rep,name=pvz,proto3" json:"pvz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPVZListResponse) Reset() {
	*x = GetPVZListResponse{}
	mi := &file_api_pvz_v1_pvz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPVZListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPVZListResponse) ProtoMessage() {}

func (x *GetPVZListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pvz_v1_pvz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPVZListResponse.ProtoReflect.Descriptor instead.
func (*GetPVZListResponse) Descriptor() ([]byte, []int) {
	return file_api_pvz_v1_pvz_proto_rawDescGZIP(), []int{1}
}

func (x *GetPVZListResponse) GetPvz() []*PVZ {
	if x != nil {
		return x.Pvz
	}
	return nil
}

var File_api_pvz_v1_pvz_proto protoreflect.FileDescriptor

const file_api_pvz_v1_pvz_proto_rawDesc = "" +
	"\n" +
	"\x14api/pvz/v1/pvz.proto\x12\x06pvz.v1\x1a\x1bgoogle/protobuf/empty.proto\")\n" +
	"\x03PVZ\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\"3\n" +
	"\x12GetPVZListResponse\x12\x1d\n" +
	"\x03pvz\x18\x01 \x03(\v2\v.pvz.v1.PVZR\x03pvz2N\n" +
	"\n" +
	"PVZService\x12@\n" +
	"\n" +
	"GetPVZList\x12\x16.google.protobuf.Empty\x1a\x1a.pvz.v1.GetPVZListResponseB Z\x1epvz-backend-service/api/pvz/v1b\x06proto3"

var (
	file_api_pvz_v1_pvz_proto_rawDescOnce sync.Once
	file_api_pvz_v1_pvz_proto_rawDescData []byte
)

func file_api_pvz_v1_pvz_proto_rawDescGZIP() []byte {
	file_api_pvz_v1_pvz_proto_rawDescOnce.Do(func() {
		file_api_pvz_v1_pvz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pvz_v1_pvz_proto_rawDesc), len(file_api_pvz_v1_pvz_proto_rawDesc)))
	})
	return file_api_pvz_v1_pvz_proto_rawDescData
}

var file_api_pvz_v1_pvz_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_pvz_v1_pvz_proto_goTypes = []any{
	(*PVZ)(nil),                // 0: pvz.v1.PVZ
	(*GetPVZListResponse)(nil), // 1: pvz.v1.GetPVZListResponse
	(*emptypb.Empty)(nil),      // 2: google.protobuf.Empty
}
var file_api_pvz_v1_pvz_proto_depIdxs = []int32{
	0, // 0: pvz.v1.GetPVZListResponse.pvz:type_name -> pvz.v1.PVZ
	2, // 1: pvz.v1.PVZService.GetPVZList:input_type -> google.protobuf.Empty
	1, // 2: pvz.v1.PVZService.GetPVZList:output_type -> pvz.v1.GetPVZListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_pvz_v1_pvz_proto_init() }
func file_api_pvz_v1_pvz_proto_init() {
	if File_api_pvz_v1_pvz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pvz_v1_pvz_proto_rawDesc), len(file_api_pvz_v1_pvz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pvz_v1_pvz_proto_goTypes,
		DependencyIndexes: file_api_pvz_v1_pvz_proto_depIdxs,
		MessageInfos:      file_api_pvz_v1_pvz_proto_msgTypes,
	}.Build()
	File_api_pvz_v1_pvz_proto = out.File
	file_api_pvz_v1_pvz_proto_goTypes = nil
	file_api_pvz_v1_pvz_proto_depIdxs = nil
}
